name: APS_2021_Matt
description: APS Matt

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  splashscreen: ^1.3.5

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo.png
    - assets/logomenu.png